export const CHART_COLORS = {
  COLOR_1: "#0B42E2",
  COLOR_2: "#63E8F2",
  COLOR_3: "#07B5FC",
  COLOR_4: "#088AF4",
  COLOR_5: "#07A2F9",
  COLOR_6: "#0972EE",
  COLOR_7: "#07C7FD",
  COLOR_8: "#3FD9FB",
  COLOR_9: "#0A5AE8",
  COLOR_10: "#87F8DD",
};

export const CHART_COLOR_ARRAY = [
  CHART_COLORS.COLOR_1,
  CHART_COLORS.COLOR_2,
  CHART_COLORS.COLOR_3,
  CHART_COLORS.COLOR_4,
  CHART_COLORS.COLOR_5,
  CHART_COLORS.COLOR_6,
  CHART_COLORS.COLOR_7,
  CHART_COLORS.COLOR_8,
  CHART_COLORS.COLOR_9,
  CHART_COLORS.COLOR_10,
];

export const getChartColorByIndex = (index: number): string => {
  return CHART_COLOR_ARRAY[index % CHART_COLOR_ARRAY.length];
};
